services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - POSTGRES_URI=${POSTGRES_URI}
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - postgres
      - mongodb
    volumes:
      - ./go-chat:/app
    networks:
      - go-chat-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://backend:8080
      - VITE_WS_URL=ws://backend:8081/ws
    depends_on:
      - backend
    networks:
      - go-chat-network

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=go_chat
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - go-chat-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=securepassword123
    volumes:
      - mongo-data:/data/db
    networks:
      - go-chat-network

networks:
  go-chat-network:
    driver: bridge

volumes:
  postgres-data:
  mongo-data: